image: samueldebruyn/debian-git

pipelines:
  default:
    - step:
        name: Deploy to test
        deployment: test   # can be test, staging or production
        script:
          - apt-get update
          - apt-get -qq install git-ftp
          - git ftp init --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://amdtllc.com/www/daycarepro/demo/
          - echo "Deploying to test environment"